// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0l7nBgY3TFfo7or2L03bbyspcW2IxaWc',
    appId: '1:892831077753:web:20d7c9c46e147adf5e8ba8',
    messagingSenderId: '892831077753',
    projectId: 'capstone4e-5423e',
    authDomain: 'capstone4e-5423e.firebaseapp.com',
    storageBucket: 'capstone4e-5423e.firebasestorage.app',
    measurementId: 'G-3VPP3NSQ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhTfQ5ujnXFrb7_O85pXOnItwFlC2j_08',
    appId: '1:892831077753:android:95c896fdffac02ce5e8ba8',
    messagingSenderId: '892831077753',
    projectId: 'capstone4e-5423e',
    storageBucket: 'capstone4e-5423e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuDGMbn91MQ_5o3SuscOztl9FMWWOLrt4',
    appId: '1:892831077753:ios:d3fdab40b4cf29915e8ba8',
    messagingSenderId: '892831077753',
    projectId: 'capstone4e-5423e',
    storageBucket: 'capstone4e-5423e.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuDGMbn91MQ_5o3SuscOztl9FMWWOLrt4',
    appId: '1:892831077753:ios:d3fdab40b4cf29915e8ba8',
    messagingSenderId: '892831077753',
    projectId: 'capstone4e-5423e',
    storageBucket: 'capstone4e-5423e.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0l7nBgY3TFfo7or2L03bbyspcW2IxaWc',
    appId: '1:892831077753:web:e8a90a57c9dafad65e8ba8',
    messagingSenderId: '892831077753',
    projectId: 'capstone4e-5423e',
    authDomain: 'capstone4e-5423e.firebaseapp.com',
    storageBucket: 'capstone4e-5423e.firebasestorage.app',
    measurementId: 'G-VEPVJE4KMH',
  );

}