import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// 1. Ensure this file exists and was generated by the FlutterFire CLI
import 'firebase_options.dart';
import 'Screens/welcome_screen.dart';
import 'Screens/navigationscreens/notification_screen.dart';

Future<void> main() async {
  // 2. Ensure Flutter bindings are initialized before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // 3. CORRECTED: Explicitly provide the platform-specific configuration
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Log the error but allow the app to run (without Firebase functionality)
    debugPrint('🚨 Firebase initializeApp failed: $e');
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        // Define your color scheme and theme customizations
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF648DDB), // highlight color
          primary: const Color(0xFF4A70A9),
          secondary: Colors.red,
          background: Colors.white,
        ),
        useMaterial3: false,
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.white,
            foregroundColor: const Color(0xFF648DDB),
            shadowColor: Colors.black26,
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(foregroundColor: Colors.red),
        ),
      ),

      // define initial route and routes
      initialRoute: '/welcome',
      routes: {
        '/welcome': (context) => const WelcomeScreen(),
        '/notifications': (context) => const NotificationScreen(),
      },
    );
  }
}
